---
version: "3.7"
services:
  cart-proxy:
    build:
      context: ./nginx
    image: cart-proxy:1.0
    depends_on:
      - cart-frontend
    ports:
      - "80:80"
    environment:
      MYSQL_HOST: cart-db
      MYSQL_DATABASE: cartdb
      MYSQL_USER: dbusername
      MYSQL_PASSWORD: dbpassword
  cart-frontend:
    build:
      context: .
    image: cart-frontend:1.0
    environment:
      MYSQL_HOST: cart-db
      MYSQL_DATABASE: cartdb
      MYSQL_USER: dbusername
      MYSQL_PASSWORD: dbpassword
  