---
version: "3.7"
services:
  product-api:
    build:
      context: .
    image: product-api
    environment:
      AWS_REGION: REGIONNAME
      TABLE_NAME: TABLENAME
  product-proxy:
    build:
      context: ./nginx
    depends_on:
      - product-api
    image: productproxy
    ports:
      - "80:80"