---
version: "3.7"
services:
  product-api:
    build:
      context: .
    image: product
    environment:
      AWS_REGION: REGIONNAME
      TABLE_NAME: TABLENAME
  product-proxy:
    build:
      context: ./nginx
    image: productproxy
    ports:
      - "80:80"
    environment:
      AWS_REGION: REGIONNAME
      TABLE_NAME: TABLENAME